[[rcodesign]]
arch = "aarch64"
git-tree-sha1 = "b3c6105b0f3ec880d0cce285e7182c1727d154f4"
os = "macos"

    [[rcodesign.download]]
    sha256 = "ba3fa10b5b001bddc9c5997eff074f1a49af3eaac97f42a810fceddd8c44ab07"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.aarch64-apple-darwin.tar.gz"
[[rcodesign]]
arch = "aarch64"
git-tree-sha1 = "4b9c60b17c991959aca0f54b48f382fdbce19027"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "e76988f52dd30638aab57c9d5c066c24b2d385637ae9327d4c673a985d13384a"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.aarch64-linux-gnu.tar.gz"
[[rcodesign]]
arch = "aarch64"
git-tree-sha1 = "f10dd9d961dad76c743bf5abcb1947a32302ab86"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "0a5325cc6895296b8ed4be3728709444e9bb4b2537ce2e98e16ef393ed0f33bd"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.aarch64-linux-musl.tar.gz"
[[rcodesign]]
arch = "powerpc64le"
git-tree-sha1 = "12f3030c542d671460babb636bef276b3fcfa908"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "199beee9ed280fca83986612845a08ea9797f33ab679fa9bddfdce56d6465da3"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.powerpc64le-linux-gnu.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "5994c949b6e8f3b9bb32e474db02ed7e905c4cc3"
os = "macos"

    [[rcodesign.download]]
    sha256 = "73dcc9c9d806e9664be4a364d247831dd42441c99b5d08069be15b65a77e00e3"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.x86_64-apple-darwin.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "fa990d1ed5a1a1d0b5c41b7eb931ed8cf388591c"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "3a76307bb3242a0a70111e4a75819ebaaa2f835ea4ae57b1e5664cf146af1b91"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.x86_64-linux-gnu.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "352f096b07866ed848dd163773dfbe249837a0a6"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "da25666bd5ea85863bac62e6aca72939df8bbbcee5fab6f07d29b8ead77dfc5e"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.x86_64-linux-musl.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "2594d27c7c0f2e15805947c082fa79216e338a1d"
os = "freebsd"

    [[rcodesign.download]]
    sha256 = "f32d8447db3a33707663c600f5d9cefb38ff5c05bd35b753fc0a36a20a7bdb37"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.x86_64-unknown-freebsd.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "e355607b730eba2fe3982efc5f153b77993c92b8"
os = "windows"

    [[rcodesign.download]]
    sha256 = "c7e8d5c9a5ba5c3822bd8eea24e34ff2ad76b8c7ae6aaf18a7682901b8d97d14"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.29.0+0/rcodesign.v0.29.0.x86_64-w64-mingw32.tar.gz"
