[[rcodesign]]
arch = "aarch64"
git-tree-sha1 = "018b31763eac4e800768165dd4a64db2bd72acdf"
os = "macos"

    [[rcodesign.download]]
    sha256 = "8c418b5365723a88531f924cfd3cdf6420009cf60ef7e877f2ed407e9cb7bc88"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.aarch64-apple-darwin.tar.gz"
[[rcodesign]]
arch = "aarch64"
git-tree-sha1 = "c10b9db5cb9551ff2cf15f06878e4d44ad12443e"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "c527d3a342a8df51c14798dd95cbab976fabc651ad4beac321f79c03f1656d86"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.aarch64-linux-gnu.tar.gz"
[[rcodesign]]
arch = "aarch64"
git-tree-sha1 = "4056d7a511fa766a265d33e1a9df636465824840"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "5f13770fc740c0cab59151f14113eff377277f194ce3b78485221743be353d28"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.aarch64-linux-musl.tar.gz"
[[rcodesign]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89160dc225c644a1a5bebb5faa889e37495774b1"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "6063ea250c6621f8bce5d86842fad5c4094d42519eaa1f26739906b2ee132484"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.armv6l-linux-gnueabihf.tar.gz"
[[rcodesign]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc6a724377a7b1569452f2841cffb8a975d80709"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "6859563fab904137c6d44cad168cd1e82d9b6422dbdb6e98faa9245aed91a275"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.armv6l-linux-musleabihf.tar.gz"
[[rcodesign]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d2d19dec28e3ec0c9f392f70fb7f02bdaf2d4cb"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "3a66b89f632a46970dfdd1205a70bd8b4c846faa69340260ff4d88e72ea4bd81"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.armv7l-linux-gnueabihf.tar.gz"
[[rcodesign]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3b0310db7ef67f2d5baa41a895fd583ab2d609f"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "fadcbbbc07945c494ceb6c78c8574bf03e382abbf5d04b6bf2e7e796113b0980"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.armv7l-linux-musleabihf.tar.gz"
[[rcodesign]]
arch = "i686"
git-tree-sha1 = "0edda9072efa410da87f5ab53940375a81071bf8"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "d1b4974a0ab802c9dab399cc29b65a4b02168216664cc4d376ff0132b6739cfb"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.i686-linux-gnu.tar.gz"
[[rcodesign]]
arch = "i686"
git-tree-sha1 = "7b021f77a483c5fe8231c1a929eef0332c745e25"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "30a3eaf58ecb428863af86ded7d47fa4c0cfbf8ae3f752f06329ab859dd22761"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.i686-linux-musl.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "fd0d8355a95175ad506ec256477b050b1bdaccde"
os = "macos"

    [[rcodesign.download]]
    sha256 = "87d39c77340b525d1b681d1b308f65cae2460cdb57771d8664d50f827572fa78"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.x86_64-apple-darwin.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "56a898a0c549d689028fe4ad043e6d96c382e1ec"
libc = "glibc"
os = "linux"

    [[rcodesign.download]]
    sha256 = "c88d213844d6df2996fca17f227fc40c964623d6b966456d4d05867258fcfbb2"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.x86_64-linux-gnu.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "afea356180c300aa9bfc83f1283a9a48eafaeb92"
libc = "musl"
os = "linux"

    [[rcodesign.download]]
    sha256 = "409c9265ca9c256c80a01b27ade657635bf5f1989e03f55e1b03aa3fca9fc44b"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.x86_64-linux-musl.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "5f34131d8578baf53ad08ee494f69d0c1974c2b3"
os = "freebsd"

    [[rcodesign.download]]
    sha256 = "9d458c65f18ec92f9e306539c36719e29a83449126fefacc333e575f01beba74"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.x86_64-unknown-freebsd.tar.gz"
[[rcodesign]]
arch = "x86_64"
git-tree-sha1 = "bbf8454567977d92ab80c3bd8897733f0f8311f1"
os = "windows"

    [[rcodesign.download]]
    sha256 = "3e6b32a3ae99823e58bdd092419d1471461ced12956e0d378e51ae9d38f2434f"
    url = "https://github.com/JuliaBinaryWrappers/rcodesign_jll.jl/releases/download/rcodesign-v0.17.0+0/rcodesign.v0.17.0.x86_64-w64-mingw32.tar.gz"
